config/routes.rb
HombuSchedule::Application.routes.draw do
  get "shihan/index"

  get "shihan/show"

  get "scheduled_class/index"

  get "scheduled_class/show"

  devise_for :users

  resources :scheduled_classes
  resources :shihans

  root :to => 'calendar#index'

end

app/models/scheduled_class.rb
class ScheduledClass < ActiveRecord::Base
  validates :time, :uniqueness => {:scope => [:day, :shihan_id]}
  belongs_to :shihan
  has_many :subbed_classes

  def self.get_days
    days = ScheduledClass.select(:day)
    days.uniq! { |day| day.day }
  end

  def self.get_times
    times = ScheduledClass.select(:time)
    times.uniq { |time| time.time }.sort { |x, y| x.time <=> y.time }
  end

  def self.get_by_day_and_time day, time
    this_class = ScheduledClass.where( {:day => day, :time => time} )
  end
end

app/models/shihan.rb
class Shihan < ActiveRecord::Base
  validates :name_en, :uniqueness => true
  has_many :scheduled_classes
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  has_many :subbed_classes
end

app/models/subbed_class.rb
class SubbedClass < ActiveRecord::Base
  belongs_to :scheduled_classes
  belongs_to :sub
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :watched_classes, Array
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :watched_classes

  def add_to_watched_classes watched_classes
    watched_classes.each do |watched_class|
      self.watched_classes << watched_class if !self.watched_classes.include?(watched_class)
      self.save
    end
  end

  def remove_from_watched_classes watched_classes
    watched_classes.each do |watched_class|
      self.watched_classes.delete(watched_class)
      self.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_filter :authenticate_user!

  # GET /calendar
  def index
    @days = ScheduledClass.get_days
    @times = ScheduledClass.get_times

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/scheduled_classes_controller.rb
class ScheduledClassesController < ApplicationController
  def index
    @scheduled_classes = ScheduledClass.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @scheduled_class = ScheduledClass.find params[:id]

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/shihans_controller.rb
class ShihansController < ApplicationController
  def index
    @shihans = Shihan.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @shihan = Shihan.find params[:id]

    respond_to do |format|
      format.html
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/scheduled_classes_helper.rb
module ScheduledClassesHelper
end

app/helpers/shihans_helper.rb
module ShihansHelper
end

app/views/calendar/index.html.erb
<h1>hello <%= current_user.email %></h1>
<h1>what we got so far</h1>

<div class="row">
  <div class="span12">
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  </div>
</div>

<div class="row-fluid">
  <% @days.each_with_index do |day, day_number| %>
    <div id="<%= day.day %>" class="row-fluid day">
      <h1 class="page-header"><small><%= day.day %></small></h1>
      <% @times.each do |time| %>
        <% classes = ScheduledClass.get_by_day_and_time( day.day, time.time ) %>
        <% classes.each do |klass| %>
          <% if klass != nil %>
            <div class="class well span2">
              <em class="time"><%= time.time %></em>
              <p class="name"><%= klass.shihan.name_en %></p>
              <p class="id" style="display:none"><%= klass.id %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="navbar navbar-fixed-bottom days-bar">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <% @days.each_with_index do |day, day_number| %>
          <li <% if day_number == 0 %>class="active" <% end %>>
            <a href="#<%= day.day %>"><%= day.day %></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HombuSchedule</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body data-spy="scroll" data-target=".navbar">
    <% if user_signed_in? %>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <ul class="nav">
              <li><%= link_to "Calendar", root_path %></li>
              <li><%= link_to "Teachers", shihans_path %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/scheduled_classes/index.html.erb
<% @scheduled_classes.each do |scheduled_class| %>
  <ul>
    <li><%= scheduled_class.day %></li>
    <li><%= scheduled_class.time %></li>
    <li><%= scheduled_class.shihan.name_en %></li>
    <li><%= link_to "Class Link", scheduled_class_path(scheduled_class) %></li>
  </ul>
<% end %>

app/views/scheduled_classes/show.html.erb
<ul>
  <li><%= @scheduled_class.day %></li>
  <li><%= @scheduled_class.time %></li>
  <li><%= @scheduled_class.shihan.name_en %></li>
</ul>

app/views/shihans/index.html.erb
<% @shihans.each do |shihan| %>
  <ul>
  <li><%= link_to "#{shihan.name_en}", shihan_path(shihan) %></li>
    <% shihan.scheduled_classes.each do |scheduled_class| %>
      <ul>
        <li><%= scheduled_class.day %></li>
        <li><%= scheduled_class.time %></li>
        <%= link_to "Class Link", scheduled_class_path(scheduled_class) %>
      </ul>
    <% end %>
  </ul>
<% end %>

app/views/shihans/show.html.erb
<ul>
  <li><%= @shihan.name_en %></li>
  <% @shihan.scheduled_classes.each do |scheduled_class| %>
    <ul>
      <li><%= scheduled_class.day %></li>
      <li><%= scheduled_class.time %></li>
    </ul>
  <% end %>
</ul>